<?php
/**
 * Target Management System - Interactive Hostinger Setup Script
 * 
 * This script will ask for all necessary information and create
 * all required files for subdirectory deployment automatically.
 * 
 * Usage: php setup_hostinger.php
 */

// Helper function to get user input
function promptUser($question, $default = null, $required = true) {
    if ($default) {
        echo "$question [$default]: ";
    } else {
        echo "$question: ";
    }
    
    $input = trim(fgets(STDIN));
    
    if (empty($input) && $default) {
        return $default;
    }
    
    if (empty($input) && $required) {
        echo " This field is required. Please try again.\n";
        return promptUser($question, $default, $required);
    }
    
    return $input;
}

// Helper function to get password input (hidden)
function promptPassword($question) {
    echo "$question: ";
    
    // Try to hide password input
    if (strtoupper(substr(PHP_OS, 0, 3)) === 'WIN') {
        // Windows - basic implementation
        $password = trim(fgets(STDIN));
    } else {
        // Unix/Linux - hide input
        system('stty -echo');
        $password = trim(fgets(STDIN));
        system('stty echo');
        echo "\n";
    }
    
    return $password;
}

// Welcome message
echo " Target Management System - Interactive Hostinger Setup\n";
echo "========================================================\n\n";

echo "This script will help you deploy your Laravel application to Hostinger\n";
echo "in a subdirectory (public_html/target/) with zero configuration hassle!\n\n";

// Check if we're in the correct directory
if (!file_exists('artisan')) {
    die(" Error: This script must be run from the Laravel root directory.\n");
}

// Step 1: Collect domain information
echo " Step 1: Domain Configuration\n";
echo "===============================\n";

$domain = promptUser("Enter your domain name (e.g., example.com)", null, true);

// Validate domain format
if (!filter_var("http://$domain", FILTER_VALIDATE_URL)) {
    echo "  Warning: Domain format may be invalid, but continuing...\n";
}

// Step 2: Collect database information
echo "\n Step 2: Database Configuration\n";
echo "=================================\n";

echo "Please enter your Hostinger MySQL database details:\n";
$dbHost = promptUser("Database Host", "localhost", true);
$dbPort = promptUser("Database Port", "3306", true);
$dbName = promptUser("Database Name", null, true);
$dbUser = promptUser("Database Username", null, true);
$dbPass = promptPassword("Database Password");

if (empty($dbPass)) {
    echo " Database password is required.\n";
    $dbPass = promptPassword("Database Password");
}

// Step 3: Deployment preferences
echo "\n Step 3: Deployment Configuration\n";
echo "===================================\n";

$appUrl = "https://$domain/target";
echo "Your application will be accessible at: $appUrl\n";

$confirm = promptUser("Is this correct? (y/n)", "y", true);
if (strtolower($confirm) !== 'y' && strtolower($confirm) !== 'yes') {
    $appUrl = promptUser("Enter the full URL for your application", $appUrl, true);
}

// Step 4: Create environment file
echo "\n Step 4: Creating configuration files...\n";
echo "==========================================\n";

// Generate APP_KEY
echo " Generating application key...\n";
$appKey = 'base64:' . base64_encode(random_bytes(32));

// Create .env file content
$envContent = "# Target Management System - Production Environment
# Auto-generated by setup_hostinger.php

APP_NAME=\"Target Management System\"
APP_ENV=production
APP_KEY=$appKey
APP_DEBUG=false
APP_URL=$appUrl
APP_TIMEZONE=UTC

LOG_CHANNEL=stack
LOG_DEPRECATIONS_CHANNEL=null
LOG_LEVEL=error

# Database Configuration
DB_CONNECTION=mysql
DB_HOST=$dbHost
DB_PORT=$dbPort
DB_DATABASE=$dbName
DB_USERNAME=$dbUser
DB_PASSWORD=$dbPass

# Broadcasting
BROADCAST_DRIVER=log

# Cache Configuration
CACHE_DRIVER=file
FILESYSTEM_DISK=local

# Queue Configuration
QUEUE_CONNECTION=sync

# Session Configuration
SESSION_DRIVER=file
SESSION_LIFETIME=120

# Mail Configuration
MAIL_MAILER=smtp
MAIL_HOST=mailpit
MAIL_PORT=1025
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=\"hello@$domain\"
MAIL_FROM_NAME=\"\${APP_NAME}\"

# AWS (not needed for Hostinger)
AWS_ACCESS_KEY_ID=
AWS_SECRET_ACCESS_KEY=
AWS_DEFAULT_REGION=us-east-1
AWS_BUCKET=
AWS_USE_PATH_STYLE_ENDPOINT=false

# Pusher (not needed for this app)
PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_HOST=
PUSHER_PORT=443
PUSHER_SCHEME=https
PUSHER_APP_CLUSTER=mt1

VITE_APP_NAME=\"\${APP_NAME}\"
VITE_PUSHER_APP_KEY=\"\${PUSHER_APP_KEY}\"
VITE_PUSHER_HOST=\"\${PUSHER_HOST}\"
VITE_PUSHER_PORT=\"\${PUSHER_PORT}\"
VITE_PUSHER_SCHEME=\"\${PUSHER_SCHEME}\"
VITE_PUSHER_APP_CLUSTER=\"\${PUSHER_APP_CLUSTER}\"
";

// Write .env file
file_put_contents('.env', $envContent);
echo " Created .env file with your configuration\n";

// Create subdirectory .htaccess file
$htaccessContent = "# Target Management System - Subdirectory Routing
# Place this file as .htaccess in your main public_html/ directory

<IfModule mod_rewrite.c>
    RewriteEngine On
    
    # Redirect /target to /target/public/ if accessing directory directly
    RewriteRule ^target/?$ target/public/ [L,R=301]
    
    # Route all /target/* requests to /target/public/*
    RewriteRule ^target/(.*)$ target/public/$1 [L]
</IfModule>

# Security: Deny access to sensitive files in subdirectory
<Files \"target/.env\">
    Order Allow,Deny
    Deny from all
</Files>

<Files \"target/composer.json\">
    Order Allow,Deny
    Deny from all
</Files>

<Files \"target/artisan\">
    Order Allow,Deny
    Deny from all
</Files>
";

file_put_contents('.htaccess.subdirectory', $htaccessContent);
echo " Created .htaccess.subdirectory file for main directory routing\n";

// Create deployment instructions
$instructionsContent = "# HOSTINGER SUBDIRECTORY DEPLOYMENT INSTRUCTIONS
# Auto-generated by setup_hostinger.php

## Your Configuration:
- Domain: $domain
- App URL: $appUrl
- Database: $dbName on $dbHost:$dbPort

## Deployment Steps:

1. Upload all files to: public_html/target/

2. Copy .htaccess.subdirectory to public_html/.htaccess:
   cp target/.htaccess.subdirectory .htaccess

3. Run deployment script from target directory:
   cd target
   php deploy_to_hostinger.php

4. Verify installation:
   php verify_deployment.php

5. Access your application:
   $appUrl

## Default Admin Credentials:
Username: admin
Password: admin123
(CHANGE THESE IMMEDIATELY AFTER FIRST LOGIN!)

## Support:
If you encounter issues, check the HOSTINGER_DEPLOYMENT_GUIDE.md file.
";

file_put_contents('DEPLOYMENT_INSTRUCTIONS.txt', $instructionsContent);
echo " Created DEPLOYMENT_INSTRUCTIONS.txt\n";
